name: LinuxBuild
on:
  workflow_dispatch:
  
  workflow_call:
  
jobs:
  build:
    name: LinuxBuild
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Installing LibVLC
        run: |
          sudo apt-get install libvlc-dev libvlccore-dev
          
      - name: Install Libraries
        run: |
          haxelib setup ~/haxelib
          haxelib install hmm --quite
          haxelib run hmm install
          
      - name: Extract current version
        id: get_version
        run: |
          CURRENT_VERSION=$(grep -oP 'build-number="\K[^"]*' Project.xml)
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
        
      - name: Compile
        run: |
          COMMIT_SHA=$(git rev-parse --short HEAD)
          CURRENT_VERSION="${{ steps.get_version.outputs.current_version }}"
            
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            NEW_VERSION="${CURRENT_VERSION/-dev/-$COMMIT_SHA}"
            haxelib run lime build linux -Dcommit_sha=$COMMIT_SHA -Dbuild_number=$NEW_VERSION
          else
            haxelib run lime build linux -Dcommit_sha=$COMMIT_SHA -Dbuild_number=$CURRENT_VERSION
          fi
          
      - name: Create Linux zip package
        run: |
          cd export/release/linux/bin/
          zip -r linux.zip .

      - name: Uploading artifact
        uses: actions/upload-artifact@v4
        with:
          name: LinuxBuild
          path: export/release/linux/bin/linux.zip
